// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	authv1 "github.com/AlexandrKhromov2005/vault-chat/api/gen/go/auth/v1"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthClient is an autogenerated mock type for the AuthClient type
type MockAuthClient struct {
	mock.Mock
}

type MockAuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthClient) EXPECT() *MockAuthClient_Expecter {
	return &MockAuthClient_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *MockAuthClient) Login(ctx context.Context, in *authv1.LoginRequest, opts ...grpc.CallOption) (*authv1.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *authv1.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.LoginRequest, ...grpc.CallOption) (*authv1.LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.LoginRequest, ...grpc.CallOption) *authv1.LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - in *authv1.LoginRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthClient_Expecter) Login(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthClient_Login_Call {
	return &MockAuthClient_Login_Call{Call: _e.mock.On("Login",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthClient_Login_Call) Run(run func(ctx context.Context, in *authv1.LoginRequest, opts ...grpc.CallOption)) *MockAuthClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*authv1.LoginRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAuthClient_Login_Call) Return(_a0 *authv1.LoginResponse, _a1 error) *MockAuthClient_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthClient_Login_Call) RunAndReturn(run func(context.Context, *authv1.LoginRequest, ...grpc.CallOption) (*authv1.LoginResponse, error)) *MockAuthClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, in, opts
func (_m *MockAuthClient) Logout(ctx context.Context, in *authv1.LogoutRequest, opts ...grpc.CallOption) (*authv1.LogoutResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 *authv1.LogoutResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.LogoutRequest, ...grpc.CallOption) (*authv1.LogoutResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.LogoutRequest, ...grpc.CallOption) *authv1.LogoutResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.LogoutResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.LogoutRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthClient_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthClient_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - in *authv1.LogoutRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthClient_Expecter) Logout(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthClient_Logout_Call {
	return &MockAuthClient_Logout_Call{Call: _e.mock.On("Logout",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthClient_Logout_Call) Run(run func(ctx context.Context, in *authv1.LogoutRequest, opts ...grpc.CallOption)) *MockAuthClient_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*authv1.LogoutRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAuthClient_Logout_Call) Return(_a0 *authv1.LogoutResponse, _a1 error) *MockAuthClient_Logout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthClient_Logout_Call) RunAndReturn(run func(context.Context, *authv1.LogoutRequest, ...grpc.CallOption) (*authv1.LogoutResponse, error)) *MockAuthClient_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, in, opts
func (_m *MockAuthClient) RefreshToken(ctx context.Context, in *authv1.RefreshTokenRequest, opts ...grpc.CallOption) (*authv1.RefreshTokenResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *authv1.RefreshTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RefreshTokenRequest, ...grpc.CallOption) (*authv1.RefreshTokenResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RefreshTokenRequest, ...grpc.CallOption) *authv1.RefreshTokenResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.RefreshTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.RefreshTokenRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthClient_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthClient_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - in *authv1.RefreshTokenRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthClient_Expecter) RefreshToken(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthClient_RefreshToken_Call {
	return &MockAuthClient_RefreshToken_Call{Call: _e.mock.On("RefreshToken",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthClient_RefreshToken_Call) Run(run func(ctx context.Context, in *authv1.RefreshTokenRequest, opts ...grpc.CallOption)) *MockAuthClient_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*authv1.RefreshTokenRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAuthClient_RefreshToken_Call) Return(_a0 *authv1.RefreshTokenResponse, _a1 error) *MockAuthClient_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthClient_RefreshToken_Call) RunAndReturn(run func(context.Context, *authv1.RefreshTokenRequest, ...grpc.CallOption) (*authv1.RefreshTokenResponse, error)) *MockAuthClient_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, in, opts
func (_m *MockAuthClient) Register(ctx context.Context, in *authv1.RegisterRequest, opts ...grpc.CallOption) (*authv1.RegisterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *authv1.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RegisterRequest, ...grpc.CallOption) (*authv1.RegisterResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RegisterRequest, ...grpc.CallOption) *authv1.RegisterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.RegisterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthClient_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthClient_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in *authv1.RegisterRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthClient_Expecter) Register(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthClient_Register_Call {
	return &MockAuthClient_Register_Call{Call: _e.mock.On("Register",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthClient_Register_Call) Run(run func(ctx context.Context, in *authv1.RegisterRequest, opts ...grpc.CallOption)) *MockAuthClient_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*authv1.RegisterRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAuthClient_Register_Call) Return(_a0 *authv1.RegisterResponse, _a1 error) *MockAuthClient_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthClient_Register_Call) RunAndReturn(run func(context.Context, *authv1.RegisterRequest, ...grpc.CallOption) (*authv1.RegisterResponse, error)) *MockAuthClient_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllSessions provides a mock function with given fields: ctx, in, opts
func (_m *MockAuthClient) RevokeAllSessions(ctx context.Context, in *authv1.RevokeAllSessionsRequest, opts ...grpc.CallOption) (*authv1.RevokeAllSessionsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllSessions")
	}

	var r0 *authv1.RevokeAllSessionsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RevokeAllSessionsRequest, ...grpc.CallOption) (*authv1.RevokeAllSessionsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RevokeAllSessionsRequest, ...grpc.CallOption) *authv1.RevokeAllSessionsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.RevokeAllSessionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.RevokeAllSessionsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthClient_RevokeAllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllSessions'
type MockAuthClient_RevokeAllSessions_Call struct {
	*mock.Call
}

// RevokeAllSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - in *authv1.RevokeAllSessionsRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthClient_Expecter) RevokeAllSessions(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthClient_RevokeAllSessions_Call {
	return &MockAuthClient_RevokeAllSessions_Call{Call: _e.mock.On("RevokeAllSessions",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthClient_RevokeAllSessions_Call) Run(run func(ctx context.Context, in *authv1.RevokeAllSessionsRequest, opts ...grpc.CallOption)) *MockAuthClient_RevokeAllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*authv1.RevokeAllSessionsRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAuthClient_RevokeAllSessions_Call) Return(_a0 *authv1.RevokeAllSessionsResponse, _a1 error) *MockAuthClient_RevokeAllSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthClient_RevokeAllSessions_Call) RunAndReturn(run func(context.Context, *authv1.RevokeAllSessionsRequest, ...grpc.CallOption) (*authv1.RevokeAllSessionsResponse, error)) *MockAuthClient_RevokeAllSessions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthClient creates a new instance of MockAuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthClient {
	mock := &MockAuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
