// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	ratelimit "github.com/AlexandrKhromov2005/vault-chat/internal/gateway/ratelimit"
)

// MockLimiter is an autogenerated mock type for the Limiter type
type MockLimiter struct {
	mock.Mock
}

type MockLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLimiter) EXPECT() *MockLimiter_Expecter {
	return &MockLimiter_Expecter{mock: &_m.Mock}
}

// Allow provides a mock function with given fields: ctx, key
func (_m *MockLimiter) Allow(ctx context.Context, key string) (ratelimit.Result, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Allow")
	}

	var r0 ratelimit.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (ratelimit.Result, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) ratelimit.Result); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(ratelimit.Result)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLimiter_Allow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allow'
type MockLimiter_Allow_Call struct {
	*mock.Call
}

// Allow is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockLimiter_Expecter) Allow(ctx interface{}, key interface{}) *MockLimiter_Allow_Call {
	return &MockLimiter_Allow_Call{Call: _e.mock.On("Allow", ctx, key)}
}

func (_c *MockLimiter_Allow_Call) Run(run func(ctx context.Context, key string)) *MockLimiter_Allow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLimiter_Allow_Call) Return(_a0 ratelimit.Result, _a1 error) *MockLimiter_Allow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLimiter_Allow_Call) RunAndReturn(run func(context.Context, string) (ratelimit.Result, error)) *MockLimiter_Allow_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLimiter creates a new instance of MockLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLimiter {
	mock := &MockLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
