// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	authv1 "github.com/AlexandrKhromov2005/vault-chat/api/gen/go/auth/v1"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockTokenValidator is an autogenerated mock type for the TokenValidator type
type MockTokenValidator struct {
	mock.Mock
}

type MockTokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenValidator) EXPECT() *MockTokenValidator_Expecter {
	return &MockTokenValidator_Expecter{mock: &_m.Mock}
}

// ValidateToken provides a mock function with given fields: ctx, in, opts
func (_m *MockTokenValidator) ValidateToken(ctx context.Context, in *authv1.ValidateTokenRequest, opts ...grpc.CallOption) (*authv1.ValidateTokenResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *authv1.ValidateTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.ValidateTokenRequest, ...grpc.CallOption) (*authv1.ValidateTokenResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.ValidateTokenRequest, ...grpc.CallOption) *authv1.ValidateTokenResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.ValidateTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.ValidateTokenRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenValidator_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockTokenValidator_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - in *authv1.ValidateTokenRequest
//   - opts ...grpc.CallOption
func (_e *MockTokenValidator_Expecter) ValidateToken(ctx interface{}, in interface{}, opts ...interface{}) *MockTokenValidator_ValidateToken_Call {
	return &MockTokenValidator_ValidateToken_Call{Call: _e.mock.On("ValidateToken",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockTokenValidator_ValidateToken_Call) Run(run func(ctx context.Context, in *authv1.ValidateTokenRequest, opts ...grpc.CallOption)) *MockTokenValidator_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*authv1.ValidateTokenRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockTokenValidator_ValidateToken_Call) Return(_a0 *authv1.ValidateTokenResponse, _a1 error) *MockTokenValidator_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenValidator_ValidateToken_Call) RunAndReturn(run func(context.Context, *authv1.ValidateTokenRequest, ...grpc.CallOption) (*authv1.ValidateTokenResponse, error)) *MockTokenValidator_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenValidator creates a new instance of MockTokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenValidator {
	mock := &MockTokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
