// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/AlexandrKhromov2005/vault-chat/internal/chat/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRoomRepository is an autogenerated mock type for the RoomRepository type
type MockRoomRepository struct {
	mock.Mock
}

type MockRoomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomRepository) EXPECT() *MockRoomRepository_Expecter {
	return &MockRoomRepository_Expecter{mock: &_m.Mock}
}

// AddChannelMember provides a mock function with given fields: ctx, roomID, actorID, userID
func (_m *MockRoomRepository) AddChannelMember(ctx context.Context, roomID string, actorID string, userID string) error {
	ret := _m.Called(ctx, roomID, actorID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddChannelMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, roomID, actorID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoomRepository_AddChannelMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddChannelMember'
type MockRoomRepository_AddChannelMember_Call struct {
	*mock.Call
}

// AddChannelMember is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - actorID string
//   - userID string
func (_e *MockRoomRepository_Expecter) AddChannelMember(ctx interface{}, roomID interface{}, actorID interface{}, userID interface{}) *MockRoomRepository_AddChannelMember_Call {
	return &MockRoomRepository_AddChannelMember_Call{Call: _e.mock.On("AddChannelMember", ctx, roomID, actorID, userID)}
}

func (_c *MockRoomRepository_AddChannelMember_Call) Run(run func(ctx context.Context, roomID string, actorID string, userID string)) *MockRoomRepository_AddChannelMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRoomRepository_AddChannelMember_Call) Return(_a0 error) *MockRoomRepository_AddChannelMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoomRepository_AddChannelMember_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockRoomRepository_AddChannelMember_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChannel provides a mock function with given fields: ctx, ownerID, name, private
func (_m *MockRoomRepository) CreateChannel(ctx context.Context, ownerID string, name string, private bool) (*domain.Room, error) {
	ret := _m.Called(ctx, ownerID, name, private)

	if len(ret) == 0 {
		panic("no return value specified for CreateChannel")
	}

	var r0 *domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*domain.Room, error)); ok {
		return rf(ctx, ownerID, name, private)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *domain.Room); ok {
		r0 = rf(ctx, ownerID, name, private)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, ownerID, name, private)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepository_CreateChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChannel'
type MockRoomRepository_CreateChannel_Call struct {
	*mock.Call
}

// CreateChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - name string
//   - private bool
func (_e *MockRoomRepository_Expecter) CreateChannel(ctx interface{}, ownerID interface{}, name interface{}, private interface{}) *MockRoomRepository_CreateChannel_Call {
	return &MockRoomRepository_CreateChannel_Call{Call: _e.mock.On("CreateChannel", ctx, ownerID, name, private)}
}

func (_c *MockRoomRepository_CreateChannel_Call) Run(run func(ctx context.Context, ownerID string, name string, private bool)) *MockRoomRepository_CreateChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockRoomRepository_CreateChannel_Call) Return(_a0 *domain.Room, _a1 error) *MockRoomRepository_CreateChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepository_CreateChannel_Call) RunAndReturn(run func(context.Context, string, string, bool) (*domain.Room, error)) *MockRoomRepository_CreateChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetForMember provides a mock function with given fields: ctx, roomID, userID
func (_m *MockRoomRepository) GetForMember(ctx context.Context, roomID string, userID string) (*domain.Room, error) {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetForMember")
	}

	var r0 *domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Room, error)); ok {
		return rf(ctx, roomID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.Room); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepository_GetForMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForMember'
type MockRoomRepository_GetForMember_Call struct {
	*mock.Call
}

// GetForMember is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - userID string
func (_e *MockRoomRepository_Expecter) GetForMember(ctx interface{}, roomID interface{}, userID interface{}) *MockRoomRepository_GetForMember_Call {
	return &MockRoomRepository_GetForMember_Call{Call: _e.mock.On("GetForMember", ctx, roomID, userID)}
}

func (_c *MockRoomRepository_GetForMember_Call) Run(run func(ctx context.Context, roomID string, userID string)) *MockRoomRepository_GetForMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRoomRepository_GetForMember_Call) Return(_a0 *domain.Room, _a1 error) *MockRoomRepository_GetForMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepository_GetForMember_Call) RunAndReturn(run func(context.Context, string, string) (*domain.Room, error)) *MockRoomRepository_GetForMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreateDirect provides a mock function with given fields: ctx, first, second
func (_m *MockRoomRepository) GetOrCreateDirect(ctx context.Context, first string, second string) (*domain.Room, error) {
	ret := _m.Called(ctx, first, second)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateDirect")
	}

	var r0 *domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Room, error)); ok {
		return rf(ctx, first, second)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.Room); ok {
		r0 = rf(ctx, first, second)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, first, second)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepository_GetOrCreateDirect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreateDirect'
type MockRoomRepository_GetOrCreateDirect_Call struct {
	*mock.Call
}

// GetOrCreateDirect is a helper method to define mock.On call
//   - ctx context.Context
//   - first string
//   - second string
func (_e *MockRoomRepository_Expecter) GetOrCreateDirect(ctx interface{}, first interface{}, second interface{}) *MockRoomRepository_GetOrCreateDirect_Call {
	return &MockRoomRepository_GetOrCreateDirect_Call{Call: _e.mock.On("GetOrCreateDirect", ctx, first, second)}
}

func (_c *MockRoomRepository_GetOrCreateDirect_Call) Run(run func(ctx context.Context, first string, second string)) *MockRoomRepository_GetOrCreateDirect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRoomRepository_GetOrCreateDirect_Call) Return(_a0 *domain.Room, _a1 error) *MockRoomRepository_GetOrCreateDirect_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepository_GetOrCreateDirect_Call) RunAndReturn(run func(context.Context, string, string) (*domain.Room, error)) *MockRoomRepository_GetOrCreateDirect_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoomRepository creates a new instance of MockRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomRepository {
	mock := &MockRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
