// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/AlexandrKhromov2005/vault-chat/internal/auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, session
func (_m *MockSessionRepository) Create(ctx context.Context, session *domain.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.Session
func (_e *MockSessionRepository_Expecter) Create(ctx interface{}, session interface{}) *MockSessionRepository_Create_Call {
	return &MockSessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockSessionRepository_Create_Call) Run(run func(ctx context.Context, session *domain.Session)) *MockSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Session))
	})
	return _c
}

func (_c *MockSessionRepository_Create_Call) Return(_a0 error) *MockSessionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Session) error) *MockSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllForUser provides a mock function with given fields: ctx, userID
func (_m *MockSessionRepository) RevokeAllForUser(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepository_RevokeAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllForUser'
type MockSessionRepository_RevokeAllForUser_Call struct {
	*mock.Call
}

// RevokeAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockSessionRepository_Expecter) RevokeAllForUser(ctx interface{}, userID interface{}) *MockSessionRepository_RevokeAllForUser_Call {
	return &MockSessionRepository_RevokeAllForUser_Call{Call: _e.mock.On("RevokeAllForUser", ctx, userID)}
}

func (_c *MockSessionRepository_RevokeAllForUser_Call) Run(run func(ctx context.Context, userID string)) *MockSessionRepository_RevokeAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionRepository_RevokeAllForUser_Call) Return(_a0 int64, _a1 error) *MockSessionRepository_RevokeAllForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepository_RevokeAllForUser_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockSessionRepository_RevokeAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeFamily provides a mock function with given fields: ctx, userID, sessionID
func (_m *MockSessionRepository) RevokeFamily(ctx context.Context, userID string, sessionID string) error {
	ret := _m.Called(ctx, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeFamily")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_RevokeFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeFamily'
type MockSessionRepository_RevokeFamily_Call struct {
	*mock.Call
}

// RevokeFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionID string
func (_e *MockSessionRepository_Expecter) RevokeFamily(ctx interface{}, userID interface{}, sessionID interface{}) *MockSessionRepository_RevokeFamily_Call {
	return &MockSessionRepository_RevokeFamily_Call{Call: _e.mock.On("RevokeFamily", ctx, userID, sessionID)}
}

func (_c *MockSessionRepository_RevokeFamily_Call) Run(run func(ctx context.Context, userID string, sessionID string)) *MockSessionRepository_RevokeFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSessionRepository_RevokeFamily_Call) Return(_a0 error) *MockSessionRepository_RevokeFamily_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_RevokeFamily_Call) RunAndReturn(run func(context.Context, string, string) error) *MockSessionRepository_RevokeFamily_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function with given fields: ctx, currentID, next
func (_m *MockSessionRepository) Rotate(ctx context.Context, currentID string, next *domain.Session) error {
	ret := _m.Called(ctx, currentID, next)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.Session) error); ok {
		r0 = rf(ctx, currentID, next)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type MockSessionRepository_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
//   - currentID string
//   - next *domain.Session
func (_e *MockSessionRepository_Expecter) Rotate(ctx interface{}, currentID interface{}, next interface{}) *MockSessionRepository_Rotate_Call {
	return &MockSessionRepository_Rotate_Call{Call: _e.mock.On("Rotate", ctx, currentID, next)}
}

func (_c *MockSessionRepository_Rotate_Call) Run(run func(ctx context.Context, currentID string, next *domain.Session)) *MockSessionRepository_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*domain.Session))
	})
	return _c
}

func (_c *MockSessionRepository_Rotate_Call) Return(_a0 error) *MockSessionRepository_Rotate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_Rotate_Call) RunAndReturn(run func(context.Context, string, *domain.Session) error) *MockSessionRepository_Rotate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
