// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	jwt "github.com/AlexandrKhromov2005/vault-chat/internal/shared/jwt"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockTokenManager is an autogenerated mock type for the TokenManager type
type MockTokenManager struct {
	mock.Mock
}

type MockTokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenManager) EXPECT() *MockTokenManager_Expecter {
	return &MockTokenManager_Expecter{mock: &_m.Mock}
}

// IssueAccessToken provides a mock function with given fields: userID, email, username
func (_m *MockTokenManager) IssueAccessToken(userID string, email string, username string) (string, time.Time, error) {
	ret := _m.Called(userID, email, username)

	if len(ret) == 0 {
		panic("no return value specified for IssueAccessToken")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, string) (string, time.Time, error)); ok {
		return rf(userID, email, username)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(userID, email, username)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) time.Time); ok {
		r1 = rf(userID, email, username)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	if rf, ok := ret.Get(2).(func(string, string, string) error); ok {
		r2 = rf(userID, email, username)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTokenManager_IssueAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueAccessToken'
type MockTokenManager_IssueAccessToken_Call struct {
	*mock.Call
}

// IssueAccessToken is a helper method to define mock.On call
//   - userID string
//   - email string
//   - username string
func (_e *MockTokenManager_Expecter) IssueAccessToken(userID interface{}, email interface{}, username interface{}) *MockTokenManager_IssueAccessToken_Call {
	return &MockTokenManager_IssueAccessToken_Call{Call: _e.mock.On("IssueAccessToken", userID, email, username)}
}

func (_c *MockTokenManager_IssueAccessToken_Call) Run(run func(userID string, email string, username string)) *MockTokenManager_IssueAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTokenManager_IssueAccessToken_Call) Return(_a0 string, _a1 time.Time, _a2 error) *MockTokenManager_IssueAccessToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTokenManager_IssueAccessToken_Call) RunAndReturn(run func(string, string, string) (string, time.Time, error)) *MockTokenManager_IssueAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// IssueRefreshToken provides a mock function with given fields: userID, email, username
func (_m *MockTokenManager) IssueRefreshToken(userID string, email string, username string) (string, time.Time, error) {
	ret := _m.Called(userID, email, username)

	if len(ret) == 0 {
		panic("no return value specified for IssueRefreshToken")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, string) (string, time.Time, error)); ok {
		return rf(userID, email, username)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(userID, email, username)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) time.Time); ok {
		r1 = rf(userID, email, username)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	if rf, ok := ret.Get(2).(func(string, string, string) error); ok {
		r2 = rf(userID, email, username)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTokenManager_IssueRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueRefreshToken'
type MockTokenManager_IssueRefreshToken_Call struct {
	*mock.Call
}

// IssueRefreshToken is a helper method to define mock.On call
//   - userID string
//   - email string
//   - username string
func (_e *MockTokenManager_Expecter) IssueRefreshToken(userID interface{}, email interface{}, username interface{}) *MockTokenManager_IssueRefreshToken_Call {
	return &MockTokenManager_IssueRefreshToken_Call{Call: _e.mock.On("IssueRefreshToken", userID, email, username)}
}

func (_c *MockTokenManager_IssueRefreshToken_Call) Run(run func(userID string, email string, username string)) *MockTokenManager_IssueRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTokenManager_IssueRefreshToken_Call) Return(_a0 string, _a1 time.Time, _a2 error) *MockTokenManager_IssueRefreshToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTokenManager_IssueRefreshToken_Call) RunAndReturn(run func(string, string, string) (string, time.Time, error)) *MockTokenManager_IssueRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: token
func (_m *MockTokenManager) Validate(token string) (*jwt.Claims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *jwt.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*jwt.Claims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *jwt.Claims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenManager_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockTokenManager_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - token string
func (_e *MockTokenManager_Expecter) Validate(token interface{}) *MockTokenManager_Validate_Call {
	return &MockTokenManager_Validate_Call{Call: _e.mock.On("Validate", token)}
}

func (_c *MockTokenManager_Validate_Call) Run(run func(token string)) *MockTokenManager_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenManager_Validate_Call) Return(_a0 *jwt.Claims, _a1 error) *MockTokenManager_Validate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenManager_Validate_Call) RunAndReturn(run func(string) (*jwt.Claims, error)) *MockTokenManager_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenManager creates a new instance of MockTokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenManager {
	mock := &MockTokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
